Repository stratisproject/StratisFullNode, pull requests merged in 2022-10, with the labels that each got.

#1067 Use dummy address for local calls by default
  src/Stratis.Features.Unity3dApi/Unity3dApiSettings.cs
Labels: dotnet6

#1068 Fix attempt to use NFTTransferIndexer with Strax
  src/Stratis.CirrusD/Program.cs
  src/Stratis.Features.Unity3dApi/Controllers/Unity3dController.cs
  src/Stratis.Features.Unity3dApi/Unity3dApiFeature.cs
  src/Stratis.StraxD/Program.cs
Labels: 1.4.0.0

#1069 Add "verboseaddressesbalances" with POST API
  src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreClient.cs
  src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreController.cs
  src/Stratis.Features.Collateral/CollateralChecker.cs
  src/Stratis.Features.FederatedPeg.IntegrationTests/NodeInitialisationTests.cs
  src/Stratis.Features.FederatedPeg.Tests/CollateralCheckerTests.cs
Labels: 1.4.0.0

#1070 Fix GatewayPairStarts test-case
  src/Stratis.Bitcoin.Features.BlockStore/Controllers/BlockStoreController.cs
Labels: 1.4.0.0

#1071 Remove unused "checkpoints" from CachedCoinView constructor
  src/Stratis.Bitcoin.Features.Consensus.Tests/CoinViews/CoinviewTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs
  src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
  src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractMinerTests.cs
Labels: 1.4.0.0

#1072 Pass ChainIndexer argument via CachedCoinView constructor
  src/Stratis.Bitcoin.Features.Consensus.Tests/CoinViews/CoinviewTests.cs
  src/Stratis.Bitcoin.Features.Consensus.Tests/TestChainFactory.cs
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/CoinView.cs
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/InMemoryCoinView.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/LoadCoinviewRule.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/PosConsensusRuleEngine.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/PowConsensusRuleEngine.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MemPoolCoinView.cs
  src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
  src/Stratis.Bitcoin.Tests/Consensus/TestInMemoryCoinView.cs
  src/Stratis.Bitcoin/Base/BaseFeature.cs
  src/Stratis.Bitcoin/Consensus/ConsensusRuleEngine.cs
  src/Stratis.Bitcoin/Consensus/IConsensusRuleEngine.cs
  src/Stratis.SmartContracts.IntegrationTests/PoW/SmartContractMinerTests.cs
Labels: 1.4.0.0

#1073 Add collateral height checks to miner and rules
  src/Stratis.Bitcoin.Features.PoA/PoAConsensusErrors.cs
  src/Stratis.Features.Collateral/CheckCollateralCommitmentHeightRule.cs
  src/Stratis.Features.Collateral/CollateralChecker.cs
  src/Stratis.Features.Collateral/CollateralPoAMiner.cs
  src/Stratis.Features.FederatedPeg.Tests/CheckCollateralCommitmentHeightRuleTests.cs
  src/Stratis.Sidechains.Networks/CirrusDev.cs
  src/Stratis.Sidechains.Networks/CirrusMain.cs
  src/Stratis.Sidechains.Networks/CirrusRegTest.cs
  src/Stratis.Sidechains.Networks/CirrusTest.cs
  src/Stratis.Sidechains.Networks/Deployments/CirrusBIP9Deployments.cs
Labels: 1.3.2.4

#1077 Bump version to 1.5.0.0
  src/FederationSetup/FederationSetup.csproj
  src/FodyNlogAdapter/FodyNlogAdapter.csproj
  src/Stratis.Bitcoin.Cli/Stratis.Bitcoin.Cli.csproj
  src/Stratis.Bitcoin.Features.Api/Stratis.Bitcoin.Features.Api.csproj
  src/Stratis.Bitcoin.Features.BlockStore/Stratis.Bitcoin.Features.BlockStore.csproj
  src/Stratis.Bitcoin.Features.ColdStaking/Stratis.Bitcoin.Features.ColdStaking.csproj
  src/Stratis.Bitcoin.Features.Consensus/Stratis.Bitcoin.Features.Consensus.csproj
  src/Stratis.Bitcoin.Features.Dns/Stratis.Bitcoin.Features.Dns.csproj
  src/Stratis.Bitcoin.Features.ExternalAPI/Stratis.Bitcoin.Features.ExternalApi.csproj
  src/Stratis.Bitcoin.Features.Interop/Stratis.Bitcoin.Features.Interop.csproj
  src/Stratis.Bitcoin.Features.LightWallet/Stratis.Bitcoin.Features.LightWallet.csproj
  src/Stratis.Bitcoin.Features.MemoryPool/Stratis.Bitcoin.Features.MemoryPool.csproj
  src/Stratis.Bitcoin.Features.Miner/Stratis.Bitcoin.Features.Miner.csproj
  src/Stratis.Bitcoin.Features.Notifications/Stratis.Bitcoin.Features.Notifications.csproj
  src/Stratis.Bitcoin.Features.PoA.IntegrationTests.Common/Stratis.Bitcoin.Features.PoA.IntegrationTests.Common.csproj
  src/Stratis.Bitcoin.Features.PoA/Stratis.Bitcoin.Features.PoA.csproj
  src/Stratis.Bitcoin.Features.RPC/Stratis.Bitcoin.Features.RPC.csproj
  src/Stratis.Bitcoin.Features.SignalR/Stratis.Bitcoin.Features.SignalR.csproj
  src/Stratis.Bitcoin.Features.SmartContracts/Stratis.Bitcoin.Features.SmartContracts.csproj
  src/Stratis.Bitcoin.Features.Wallet/Stratis.Bitcoin.Features.Wallet.csproj
  src/Stratis.Bitcoin.Features.WatchOnlyWallet/Stratis.Bitcoin.Features.WatchOnlyWallet.csproj
  src/Stratis.Bitcoin.IntegrationTests.Common/Stratis.Bitcoin.IntegrationTests.Common.csproj
  src/Stratis.Bitcoin.Networks/Stratis.Bitcoin.Networks.csproj
  src/Stratis.Bitcoin.Tests.Common/Stratis.Bitcoin.Tests.Common.csproj
  src/Stratis.Bitcoin/Properties/AssemblyInfo.cs
  src/Stratis.Bitcoin/Stratis.Bitcoin.csproj
  src/Stratis.CirrusD/Stratis.CirrusD.csproj
  src/Stratis.CirrusDnsD/Stratis.CirrusDnsD.csproj
  src/Stratis.CirrusMinerD/Stratis.CirrusMinerD.csproj
  src/Stratis.CirrusPegD/Stratis.CirrusPegD.csproj
  src/Stratis.Features.Diagnostic/Stratis.Features.Diagnostic.csproj
  src/Stratis.Features.SQLiteWalletRepository/Stratis.Features.SQLiteWalletRepository.csproj
  src/Stratis.Features.Unity3dApi/LocalCallContract.cs
  src/Stratis.Sidechains.Networks/Stratis.Sidechains.Networks.csproj
  src/Stratis.StraxD/Stratis.StraxD.csproj
  src/Stratis.StraxDnsD/Stratis.StraxDnsD.csproj
Labels: 1.5.0.0

#1079 Fix GetBlockData
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
Labels: 1.5.0.0

#1080 Fix endianness of delete on rewind table
  src/Stratis.Bitcoin.Features.BlockStore.Tests/AddressIndexerTests.cs
  src/Stratis.Bitcoin.Features.BlockStore/AddressIndexing/AddressIndexer.cs
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/Coindb/Coindb.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/LoadCoinviewRule.cs
  src/Stratis.Bitcoin.IntegrationTests/NodeContext.cs
  src/Stratis.Bitcoin/Consensus/IConsensusRuleEngine.cs
  src/Stratis.Bitcoin/Database/ReadWriteBatch.cs
Labels: 1.5.0.0

#1082 Fix EnableAutoKickAsync
  src/Stratis.Bitcoin.Features.PoA.IntegrationTests/EnableVoteKickingTests.cs
  src/Stratis.Bitcoin.Features.PoA/Voting/VotingManager.cs
Labels: 1.5.0.0

#1081 Fix TestDBreezeSerialization test case
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/Coindb/Coindb.cs
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/Coindb/ICoindb.cs
  src/Stratis.Bitcoin.IntegrationTests/CoinViewTests.cs
Labels: 1.5.0.0
