Repository stratisproject/StratisFullNode, pull requests merged in 2022-01, with the labels that each got.

#831 Simplify mining stats
  src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs
Labels: 1.1.2.0

#834 [PoA] Remove JoinFederationRequestMonitor check
  src/Stratis.Bitcoin.Features.PoA/Voting/VotingManager.cs
  src/Stratis.Features.Collateral/CollateralPoAMiner.cs
  src/Stratis.Features.Collateral/JoinFederationRequestMonitor.cs
Labels: 1.1.2.0

#835 Improve LastRemovalEventId determinism by adding ordering
  src/Stratis.Bitcoin.Features.PoA/Voting/JoinFederationRequestService.cs
  src/Stratis.Features.Collateral/JoinFederationRequestMonitor.cs
Labels: 1.1.2.0

#836 [Cirrus] Re-introduce MandatoryCollateralMemberVotingRule
  src/Stratis.Bitcoin.Features.PoA/PoAConsensusErrors.cs
  src/Stratis.Features.Collateral/ConsensusRules/MandatoryCollateralMemberVotingRule.cs
  src/Stratis.Features.Collateral/DynamicMembershipFeature.cs
Labels: 1.1.2.0

#838 [NLog] Show calling method when logging via NLog
  src/Stratis.Bitcoin/Configuration/Logging/ILogger.cs
  src/Stratis.Bitcoin/Configuration/Logging/LoggingConfiguration.cs
Labels: 1.2.0.0

#843 [Cirrus] Don't cache next mining timestamp
  src/Stratis.Bitcoin.Features.PoA/PoAMiner.cs
Labels: 1.2.0.0

#845 Fix doco warnings in Consensus rules
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/CoinviewRule.cs
  src/Stratis.Features.Collateral/ConsensusRules/MandatoryCollateralMemberVotingRule.cs
Labels: 1.2.0.0

#849 Enable selective coinview "Rewind" optimisation
  src/Stratis.Bitcoin.Features.Consensus.Tests/Rules/TestRulesContext.cs
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/CachedCoinView.cs
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/CoinView.cs
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/Coindb/DBreezeCoindb.cs
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/Coindb/ICoindb.cs
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/Coindb/LeveldbCoindb.cs
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/Coindb/RocksDbCoindb.cs
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/InMemoryCoinView.cs
  src/Stratis.Bitcoin.Features.Consensus/Rules/PowConsensusRuleEngine.cs
  src/Stratis.Bitcoin.Features.Consensus/StakeChainStore.cs
  src/Stratis.Bitcoin.Features.MemoryPool/MemPoolCoinView.cs
  src/Stratis.Bitcoin.IntegrationTests/CoinViewTester.cs
  src/Stratis.Bitcoin.Tests/Consensus/TestInMemoryCoinView.cs
  src/Stratis.Bitcoin/Consensus/ConsensusManager.cs
  src/Stratis.Bitcoin/Consensus/ConsensusRuleEngine.cs
  src/Stratis.Bitcoin/Consensus/IConsensusRuleEngine.cs
Labels: 1.2.1.0

#851 [NLog] Fix release-mode logging in controllers
  src/Stratis.Bitcoin/Configuration/Logging/ILogger.cs
  src/Stratis.Bitcoin/Configuration/Logging/LogManager.cs
  src/Stratis.Bitcoin/Configuration/Logging/LoggerFactory.cs
Labels: 1.2.0.0

#713 Add BIP9 ActivationHeightProvider
  src/Stratis.Bitcoin.Features.Consensus/Rules/CommonRules/HeaderVersionRule.cs
  src/Stratis.Bitcoin.Tests/Base/Deployments/ActivationHeightProviderTest.cs
  src/Stratis.Bitcoin/Base/Deployments/ActivationHeightProvider.cs
  src/Stratis.Bitcoin/Base/Deployments/NodeDeployments.cs
  src/Stratis.Bitcoin/Base/Deployments/ThresholdConditionCache.cs
Labels: 1.2.1.0

#852 Optimise LeveldbCoindb Rewind
  src/Stratis.Bitcoin.Features.Consensus/CoinViews/Coindb/LeveldbCoindb.cs
Labels: 1.2.1.0

#858 Fix NBitcoin copyright date
  src/NBitcoin/NBitcoin.csproj
  src/Stratis.Bitcoin.Tests/PackagesAndVersions/PackagesAndVersionsTests.cs
Labels: 1.2.1.0

#855 Update LevelDb to Stratis implementation
  src/Stratis.Bitcoin.Features.Consensus/Stratis.Bitcoin.Features.Consensus.csproj
  src/Stratis.Bitcoin/Stratis.Bitcoin.csproj
Labels: 1.2.1.0

#848 Resolve missing Key.GetHashCode override
  src/Stratis.Patricia/Key.cs
Labels: 1.2.1.0

#841 [Cirrus] Use voting requests with add member polls tests
  src/Stratis.Bitcoin.Features.PoA.Tests/PoATestsBase.cs
  src/Stratis.Bitcoin.Features.PoA.Tests/SlotsManagerTests.cs
  src/Stratis.Bitcoin.Features.PoA.Tests/VotingManagerTests.cs
Labels: 1.2.1.0

#842 [Cirrus] Fix poll sanitization
  src/Stratis.Bitcoin.Features.PoA.Tests/VotingManagerTests.cs
  src/Stratis.Bitcoin.Features.PoA/Voting/VotingManager.cs
  src/Stratis.Features.Collateral/JoinFederationRequestMonitor.cs
Labels: 1.2.1.0

#865 Resolve warnings found in Stratis.Bitcoin.Features.RPC
  src/Stratis.Bitcoin.Features.RPC/RPCClient.cs
Labels: 1.2.1.0
